### ISSUE TITLE
Lua script attempted to access a non local key in a cluster node

### ISSUE THREAD

**Issue by adomass** [cristipufu/aspnetcore-redis-rate-limiting#25]
Using AWS ElasticCache:

```
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_d3a858ae047422548b35753d09e9d2fe57ec91c0): @user_script:2: @user_script: 2: Lua script attempted to access a non local key in a cluster node
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1909
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1501
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(LuaScript script, Object parameters, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1536
   at RedisRateLimiting.Concurrency.RedisFixedWindowManager.TryAcquireLease()
   at RedisRateLimiting.RedisFixedWindowRateLimiter`1.AttemptAcquireCore(Int32 permitCount)

```

**Comment by cristipufu** [comment]
Hi @adomass 

Thanks for taking the time to open this issue!

Can I please ask you to give this PR a try before merging it and releasing a new library version?

PR https://github.com/cristipufu/aspnetcore-redis-rate-limiting/pull/26 (set the `appsettings.json` Redis connection string and try to run the tests)

**Comment by adomass** [comment]
Hi @cristipufu 
Its a bit tricky to test it since i cannot access AWS ElasticCache from local machine. I will try to build dll from your pr ant reference it deploy to our aws test env

**Comment by cristipufu** [comment]
@adomass I pushed the changes, please update and let me know if it works, thanks!

**Comment by adomass** [comment]
Unfortunatelly i still get same error. Could it be that you need to access key in lua script using KEYS[1]. Not sure how that works

**Comment by adomass** [comment]
Or maybe you need to pass
local expires_at_key = @rate_limit_key .. "":exp"" as RedisKey parameter as well to lua sciprt?
I am  using  RedisFixedWindowRateLimiter

**Comment by cristipufu** [comment]
Can you please try with the RedisSlidingWindowRateLimiter?

**Comment by adomass** [comment]
It has only one key I suppose so if our hypothesis is correct it should work. I will try

**Comment by adomass** [comment]
I was testing how sliding window works. Looks like not  exactly like [documented](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/#sliding-window-limit) but good enough. 

But it works on AWS. So it must be a problem with second key!

**Comment by cristipufu** [comment]
Appreciate your help!

**Comment by adomass** [comment]
@cristipufu Now i tested FixedWindow and i get different eror now :)

`StackExchange.Redis.RedisCommandException: Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot`

**Comment by adomass** [comment]
I think i know the issue. Try this:

```
RateLimitKey = new RedisKey($"rl:{{{partitionKey}}}");
RateLimitExpireKey = new RedisKey($"rl:{{{partitionKey}}}:exp");
```

**Comment by cristipufu** [comment]
Pushed changes, please let me know if it works

**Comment by adomass** [comment]
@cristipufu now it works with fixed window as well. Thanks for fixing it so quickly. I would have had to use different library otherwise, but I wanted to use this out  of the box .net 7 feature with redis so its great that now it works on AWS as well.
Well done! 👍

**Comment by odin568** [comment]
Hi,
not sure if related or if I should create a new ticket.
I am using sliding window approach and sometimes get following exception. It is just a handful out of thousand requests:
```
StackExchange.Redis.RedisCommandException: Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot
   at bool StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge<T>(Message message, ResultProcessor<T> processor, IResultBox<T> resultBox, ref ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1955
   at ValueTask<WriteResult> StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridgeAsync<T>(Message message, ResultProcessor<T> processor, IResultBox<T> resultBox, ref ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2013
   at Task<T> StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl<T>(Message message, ResultProcessor<T> processor, object state, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2125
   at Task<T> StackExchange.Redis.RedisBase.ExecuteAsync<T>(Message message, ResultProcessor<T> processor, T defaultValue, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 47
   at async Task<RedisResult> StackExchange.Redis.RedisDatabase.ScriptEvaluateAsync(string script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1551
   at async Task<RedisSlidingWindowResponse> RedisRateLimiting.Concurrency.RedisSlidingWindowManager.TryAcquireLeaseAsync(string requestId)
   at async ValueTask<RateLimitLease> RedisRateLimiting.RedisSlidingWindowRateLimiter<TKey>.AcquireAsyncCoreInternal()
   at async ValueTask<LeaseContext> Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.CombinedWaitAsync(HttpContext context, CancellationToken cancellationToken)
   at async ValueTask<LeaseContext> Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.TryAcquireAsync(HttpContext context, MetricsContext metricsContext)
   at async Task Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at async Task Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
```

Any clue what might caused this issue? What other information you would need?

Thanks a lot btw for this fantastic library!
